In [1]:
# numpy的使用

In [2]:
# 1. numpy的属性
#   ndim 维度
#   shape 行数和列数
#   size  元素个数

In [3]:
import numpy as np

In [4]:
# 将列表转换为矩阵
array = np.array([[1,2,3],[2,3,4]])

In [5]:
array

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
# 维度
array.ndim

2

In [7]:
# 行数和列数
array.shape

(2, 3)

In [8]:
# 元素个数
array.size

6

In [9]:
# 2. Numpy 创建array

In [10]:
# array 创建数组
# dtype 指定数据类型
# zeros 创建数据全为0
# ones 创建数据全为1
# empty 创建数据接近0，非0
# arrange  按指定范围内创建数据
# linspace 创建等差数列

In [11]:
# 创建数组
a = np.array([2,23,4])
a

array([ 2, 23,  4])

In [12]:
# 指定数据dtype
a = np.array([2,23,4], dtype=np.int)
a.dtype

dtype('int64')

In [13]:
a = np.array([2,23,4], dtype =np.float32)
a.dtype

dtype('float32')

In [14]:
a = np.array([2,23,4], dtype =np.int32)
a.dtype

dtype('int32')

In [15]:
a = np.array([2,23,4], dtype = np.float32)
a.dtype

dtype('float32')

In [16]:
# 创建特定数据

In [17]:
a = np.array([[2,23,4],[2,32,4]])
a

array([[ 2, 23,  4],
       [ 2, 32,  4]])

In [19]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a = np.ones((3,4), dtype=np.int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
a = np.empty((3,4))
a

array([[1.49166815e-154, 3.11107871e+231, 2.37663529e-312,
        2.14321575e-312],
       [2.37663529e-312, 2.56761491e-312, 8.48798317e-313,
        9.33678148e-313],
       [8.70018275e-313, 2.12199579e-313, 4.79243676e-322,
        8.34402697e-309]])

In [22]:
a = np.arange(10,20,2)  # 10-19,步长为2
a

array([10, 12, 14, 16, 18])

In [23]:
# 使用reshape改变数据的形状
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# 使用linspace创建线段型数据，等差数列
a = np.linspace(1,10,19) # 开始1，结束10，分割为19个数据，生成线段
a

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [26]:
# 更改形状
a = np.linspace(1,10,20).reshape((5,4))
a

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [27]:
# 3.Numpy 的基础运算

In [28]:
import numpy as np

In [29]:
a = np.array([10,20,30,40])
b = np.arange(4)

In [37]:
a

array([10, 20, 30, 40])

In [38]:
b

array([0, 1, 2, 3])

In [30]:
# a和b是两个属性为array，也就是矩阵的变量
# 而且两者都是1行4列的矩阵，其中b矩阵中的元素分别是从0到3.

In [31]:
# 如果我们想求两个矩阵之间的减法，可以尝试输入：
c = a- b
c # 得到对应元素相减的结果

array([10, 19, 28, 37])

In [34]:
# 同理，矩阵对应元素的相加和相乘也可以用类似的方式表示。

In [35]:
# 加法
c = a+b
c

array([10, 21, 32, 43])

In [36]:
# 乘法
c = a*b  # 元素一一对应相乘
c

array([  0,  20,  60, 120])

In [39]:
# 有所不同的是，在numpy中，
# 想要求出矩阵中各个元素的乘方需要依赖双星符号**,
# 以二次方举例
c = b**2
c

array([0, 1, 4, 9])

In [41]:
# Numpy中具有很多的数据函数工具，比如三角函数等，
# 当我们需要对矩阵中每一项元素进行函数运算时，可以很简便的调用它们。
# 以sin函数为例。
c = 10 * np.sin(a)
c

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [42]:
# 除了函数应用外，还能进行逻辑判断
b<3

array([ True,  True,  True, False])

In [43]:
b ==3

array([False, False, False,  True])

In [44]:
# 上述运算均是简历在一维矩阵上，即只有一行的矩阵上面的计算，
# 如果我们想要对多维度的矩阵进行操作。

In [45]:
# ==== ndim>1 =====

In [46]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))

In [47]:
a

array([[1, 1],
       [0, 1]])

In [48]:
b

array([[0, 1],
       [2, 3]])

In [49]:
# 矩阵乘法分为两种
# 1. 是和上面一维的一样，数组中的对应元素相乘
# 2. 是标准的矩阵乘法运算，即对应行乘以对应列得到相应的元素。

In [50]:
c_dot = np.dot(a,b)
c_dot

array([[2, 4],
       [2, 3]])

In [52]:
# sum(), min(), max()的使用

In [53]:
a = np.random.random((2,4))
a

array([[0.54744796, 0.91472862, 0.7395385 , 0.15835102],
       [0.01855918, 0.82487926, 0.28008059, 0.61273301]])

In [56]:
# 对元素进行求和以及寻找极值的操作
print('对矩阵的所有元素进行求和：',np.sum(a))
print('求矩阵的最小值：',np.min(a))
print('求矩阵的最大值：',np.max(a))

对矩阵的所有元素进行求和： 4.096318136879612
求矩阵的最小值： 0.018559179993760888
求矩阵的最大值： 0.9147286156158135


In [58]:
# 如果需要对行或者列进行查找运算，就需要axis参数。
# axis = 0 代表跨行  === > 即计算行上面的所有的列的值
# axis = 1 代表跨列  === > 即计算列上面的所有的行的值。

# 当axis=0时，将会以列作为查找单元；
# 当axis=1时，将会以行作为查找单元。

In [60]:
print('a:',a)
print('colum sum=',np.sum(a,axis=0))
print('row sum=',np.sum(a,axis=1))
print('row max=',np.max(a,axis=1))

a: [[0.54744796 0.91472862 0.7395385  0.15835102]
 [0.01855918 0.82487926 0.28008059 0.61273301]]
colum sum= [0.56600714 1.73960787 1.0196191  0.77108403]
row sum= [2.36006609 1.73625205]
row max= [0.91472862 0.82487926]


In [62]:
# 4.索引和常用函数

In [63]:
import numpy as np

In [64]:
A = np.arange(2,14).reshape((3,4))
A 

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [68]:
# 求矩阵中最小元素的索引
print(np.argmin(A)) 

# 求矩阵中最大元素的索引
print(np.argmax(A))

0
11


In [70]:
# 均值
print(np.mean(A))
print(np.average(A))

7.5
7.5


In [74]:
# 均值的另一种写法
print(A.mean())

7.5


In [79]:
# 累积函数cumsum()
np.cumsum(A)
# 生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和。

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [80]:
# 累差运算
np.diff(A)
# 计算的是每一行中后一项与前一项之差。
# 故一个3*4的矩阵通过函数计算得到的矩阵便是3*3的矩阵。

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [83]:
print(A)

print('>>>',np.nonzero(A))
# 这个函数将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵。

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
>>> (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [84]:
# 对所有元素进行仿照列表一样的排序操作
# 这里的排序函数任然仅针对每一行进行从小到大排序操作
A = np.arange(14,2,-1).reshape((3,4))
A

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [85]:
np.sort(A)

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

In [86]:
# 矩阵的转置：
# 两种方法：A.T，
#         np.transpose(A)
print(np.transpose(A))
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [87]:
# clip()函数
print(A)
print(np.clip(A,5,9))

# clip()函数的格式是clip(Array, Array_min, Array_max)
# Array是将要被执行用的矩阵，
# Array_min用于让函数判断矩阵中的元素是否有比最小值小的，
# Array_max用于让函数判断矩阵中的元素是否有比最大值大的。
# 将这些指定的元素转换为最小值或者最大值。

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [88]:
# 一维索引

In [89]:
# 在元素列表或数组中，我们可以用如a[2]一样的表示方法，也有其对应的表示方法

In [90]:
import numpy as np

In [91]:
A = np.arange(3,15)
A

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
A[3]

6

In [95]:
# 将矩阵转换为二维的
A = np.arange(3,15).reshape((3,4))
print(A)
print()
print('A[2]:',A[2]) # 这时的A[2]对应的就是矩阵A中的第三行的所有元素。

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]

A[2]: [11 12 13 14]


In [96]:
# 二维索引

In [98]:
# 如果想要表示具体的单个元素
print(A[1][1]) # 取矩阵中第二行第二列的元素8
print(A[1,1]) # 同上

8
8


In [99]:
# 在Python的list中，我们可以用“:“对一定范围内的元素进行切片操作。
# 在Numpy中我们依然可以给出相应的方法：
print(A[1,1:3])

[8 9]


In [100]:
# 利用for循环逐行打印行
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [101]:
# 逐行打印列
for column in A.T: # 对A进行转置，再将得到的矩阵逐行输出即可得到原矩阵的逐列输出。
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [102]:
# 有关迭代输出的问题：
import numpy as np
A = np.arange(3,15).reshape((3,4))

print(A.flatten()) 
# flatten是一个展开性质的函数，将多维的矩阵进行展开成1列的数列。

for item in A.flat: # flat是一个迭代器，本身是一个object属性。
    print('>>>',item)


[ 3  4  5  6  7  8  9 10 11 12 13 14]
>>> 3
>>> 4
>>> 5
>>> 6
>>> 7
>>> 8
>>> 9
>>> 10
>>> 11
>>> 12
>>> 13
>>> 14


In [ ]:
# 5. Numpy array 合并

In [103]:
# 对于一个array的合并，我们可以想到按行、按列等多种方式进行合并。
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])

In [105]:
print(A)
print()
print(B)

[1 1 1]

[2 2 2]


In [ ]:
# 堆叠数组的函数 stack(), hstack(), vstack()

In [106]:
# vertical stack
np.vstack((A,B))

# vstack((tup)) 
# 参数tup可以是元组，列表，或者numpy数组，返回结果为numpy的数组
# 它是垂直（按照行顺序）的把数组给堆叠起来。

array([[1, 1, 1],
       [2, 2, 2]])

In [107]:
# vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作。

In [108]:
C = np.vstack((A,B))
print(A.shape)
print(C.shape)

(3,)
(2, 3)


In [109]:
# 利用shape函数可以让我们很容易地知道A和C的属性，从打印出的结果来看，
# A仅仅是一个拥有3个元素的数组（数列），而合并后得到的C是一个2行3列的矩阵。

In [110]:
# np.hstack() 左右合并 horizontal stack

In [111]:
D = np.hstack((A,B))
print(D)
print()
print(A.shape,D.shape)

[1 1 1 2 2 2]

(3,) (6,)


In [112]:
# 打印出的结果：D本身来源于A，B两个数列的左右合并，
# 而且新生成的D本身也是一个含有6项元素的序列。

In [123]:
# np.newaxis()
# 说完了array的合并，

Help on function stack in module numpy.core.shape_base:

stack(arrays, axis=0, out=None)
    Join a sequence of arrays along a new axis.
    
    The `axis` parameter specifies the index of the new axis in the dimensions
    of the result. For example, if ``axis=0`` it will be the first dimension
    and if ``axis=-1`` it will be the last dimension.
    
    .. versionadded:: 1.10.0
    
    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.
    axis : int, optional
        The axis in the result array along which the input arrays are stacked.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what stack would have returned if no
        out argument were specified.
    
    Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.
    
    See Also
    --------
    concatenate : Join a seq

In [125]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.stack((a,b))
np.stack((a,b),axis=-1)

array([[1, 2],
       [2, 3],
       [3, 4]])